### PR TITLE
Feature/pdfocr

### PR DESCRIPTION
**Pull request by marcr-ilovepdf**
New features:
- Adds pdfocr tool to the library.
- Adds missing parameters to `listSignatures`.

Changes:
- Now TaskFactory typechecks all tools are present.
- Updated dependencies.

Fixes:
- Fix several signature tests.

### CODE REVIEW

**Review by diego-ilovepdf — CHANGES_REQUESTED** [review]
This comment is more for me:

1. Change Github workflow keys
2. Take a look of the task factory
3. Refactor inRange?

**Comment by marcr-ilovepdf** [comment]
Do you want me to replace all `inRange` occurrences with the expectations pair? I only did those of the tests I had to fix.
Or do you want a helper that contains the expectations?
```js
const expectInRange = (actual, expected, errorMargin) => {
    expect(data.length).toBeGreaterThan(expected - errorMargin)
    expect(data.length).toBeLessThan(expected + errorMargin)
}
```

**Comment by diego-ilovepdf** [comment]
> Do you want me to replace all `inRange` occurrences with the expectations pair? I only did those of the tests I had to fix. Or do you want a helper that contains the expectations?
> 
> ```js
> const expectInRange = (actual, expected, errorMargin) => {
>     expect(data.length).toBeGreaterThan(expected - errorMargin)
>     expect(data.length).toBeLessThan(expected + errorMargin)
> }
> ```

Exactly 👍

**Comment by diego-ilovepdf** [comment]
@marcr-ilovepdf could you take a look about why is not passing the tests? I thought that it was something related to the keys, but it seems that axios library was not well-updated https://github.com/ilovepdf/ilovepdf-js-core/actions/runs/10095828009/job/27916895127?pr=1

**Pull request merged**
